<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<p><?php /* @escapeNotVerified */ echo __('Sorry, Unable to process your order') ?>
<?php if ($block->getRealOrderId()) : ?>(<?php /* @escapeNotVerified */ echo __('Order #') . $block->getRealOrderId() ?>)<?php endif ?></p>
<?php if ($error = $block->getErrorMessage()) : ?><p><?php /* @escapeNotVerified */ echo __('Error :') .$error ?></p><?php endif ?>
<p><?php /* @escapeNotVerified */ echo __('Click <a href="%1">here</a> to continue shopping.', $block->escapeUrl($block->getContinueShoppingUrl())) ?></p>