<footer class="footer-container">



	



	<div class="footer-top">



		<div class="container">



			<?php echo $this->getChildHtml('footer_static')?>



			



		</div>



	</div>



	<div class="footer-bottom">



		<div class="container">



			<div class="row">



				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">



					<?php echo $this->getChildHtml('footer.copyright')?>



				</div>



				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">



					<?php echo $this->getChildHtml('footer_payment')?>



				</div>



			</div>



			<div id="back_top">



				<a href="#back-top"><span><?php /* @escapeNotVerified */ echo __('top'); ?></span></a>



			</div>



		</div>



	</div>



</footer>



<script type="text/javascript">



			



	require(["jquery"], function($){







	   $(window).scroll(function() {



			if($(this).scrollTop() > 300) {



				$('#back_top').fadeIn();   



			} else {



				$('#back_top').fadeOut();



			}



		});



		   $('#back_top').click(function() {



			$('body,html').animate({scrollTop:0},500);



		}); 



	   



	});



</script>



<!-- 23 Jan 2018 -->


<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-112865137-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-112865137-1');
</script>



<!-- Facebook Pixel Code -->

<script>

!function(f,b,e,v,n,t,s)

{if(f.fbq)return;n=f.fbq=function(){n.callMethod?

n.callMethod.apply(n,arguments):n.queue.push(arguments)};

if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';

n.queue=[];t=b.createElement(e);t.async=!0;

t.src=v;s=b.getElementsByTagName(e)[0];

s.parentNode.insertBefore(t,s)}(window,document,'script',

'https://connect.facebook.net/en_US/fbevents.js');

fbq('init', '2037714566504816'); 

fbq('track', 'PageView');

</script>

<noscript>

<img height="1" width="1"

src="https://www.facebook.com/tr?id=2037714566504816&ev=PageView

&noscript=1"/>

</noscript>

<!-- End Facebook Pixel Code -->





