<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_invoice = $block->getInvoice() ?>
<?php $_order   = $block->getOrder() ?>
<?php if ($_invoice && $_order): ?>
    <table class="email-items">
       <thead style="background-color:#EDEBEB;">
            <tr>
                <th class="item-info" style="vertical-align:middle">
                    <?= /* @escapeNotVerified */  __('Items'); ?>
                </th>
                <th class="col cgst" style="vertical-align:middle" colspan="2">
					<table>
                      <tbody style="background:none;text-align:center">
                    	<tr>
                        	<td colspan="2"><?php /* @escapeNotVerified */ echo __('CGST') ?></span></td>
                        </tr>
                        <tr>
                        	<td><?php echo __('Rate') ?></span></td>
                            <td><?php echo __('Amount') ?></span></td>
                        </tr>
                       </tbody>
                    </table>
				</th>
                <th class="col sgst" style="vertical-align:middle" colspan="2">
                	<table>
                      <tbody style="background:none;text-align:center">
                    	<tr>
                        	<td colspan="2"><?php /* @escapeNotVerified */ echo __('SGST') ?></span></td>
                        </tr>
                        <tr>
                        	<td><?php echo __('Rate') ?></span></td>
                            <td><?php echo __('Amount') ?></span></td>
                        </tr>
                       </tbody>
                    </table>
                </th>
                <th class="col igst" style="vertical-align:middle" colspan="2">
                	<table>
                      <tbody style="background:none;text-align:center">
                    	<tr>
                        	<td colspan="2"><?php /* @escapeNotVerified */ echo __('IGST') ?></span></td>
                        </tr>
                        <tr>
                        	<td><?php echo __('Rate') ?></span></td>
                            <td><?php echo __('Amount') ?></span></td>
                        </tr>
                       </tbody>
                    </table>
                </th>
                <th class="item-qty" style="vertical-align:middle">
                    <?= /* @escapeNotVerified */  __('Qty'); ?>
                </th>
                <th class="item-subtotal" style="vertical-align:middle">
                    <?= /* @escapeNotVerified */  __('Subtotal'); ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($_invoice->getAllItems() as $_item): ?>
            <?php
                if ($_item->getOrderItem()->getParentItem()) {
                    continue;
                }
            ?>
            <tbody>
                <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
        <tfoot class="order-totals">
            <?= $block->getChildHtml('invoice_totals') ?>
        </tfoot>
    </table>
<?php endif; ?>
