<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * BSS Commerce does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * BSS Commerce does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   BSS
 * @package    Bss_FBT
 * @author     Extension Team
 * @copyright  Copyright (c) 2015-2016 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>

<?php
$helper = $this->helper('Bss\FBT\Helper\Data');
$storeManager = \Magento\Framework\App\ObjectManager::getInstance()->get('\Magento\Store\Model\StoreManagerInterface');
?>
<?php if ($helper->isActive()): ?>
    
<?php
$type = 'fbt';
$class = $type;
$image = 'related_products_list';
$title = $helper->getLTitle();
$limit = 0;
$shuffle = 0;
$canItemsAddToCart = true;
$showAddTo = true;
$showCart = true;
$templateType = $helper->getShowReview();
$description = false;
$items = $block->getItemsFbt();
$limit = $helper->getLLimitProduct();
$kj = [];
?>

<?php if ($items && count($items) > 0):?>
<form action="<?php  echo $storeManager->getStore()->getBaseUrl().'fbt/cart/addMultiple'; ?>" method="post" id="fbt-products" class="fbt-product-list">
<div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
    <div class="block-title title">
        <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">

        <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
            <ol class="products list items product-items">
            <!-- Current product -->
            <?php if ($helper->getShowCurentProduct()) : ?>
                    <?php $productcurrent = $block->getCurrentProduct() ;?>
                        <li class="item li0 fbt_<?php echo $productcurrent->getId() ?> product product-item">
                            <div class="product-item-info ">
                                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($productcurrent) ?>" class="product photo product-item-photo">
                                    <?php echo $block->getImage($productcurrent, $image)->toHtml(); ?>
                                </a>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($productcurrent->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($productcurrent) ?>">
                                        <?php echo $block->escapeHtml($productcurrent->getName()) ?></a>
                                    </strong>
                                    <div class="price-fbt-item" style="<?php echo $helper->getShowPrice()? '':'display:none' ?>">
                                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($productcurrent); ?>
                                    </div>
                                        <?php if ($templateType): ?>
                                            <?php echo $block->getReviewsSummaryHtml($productcurrent, 'short',true) ?>
                                        <?php endif; ?>
                                        <?php if ($helper->getDisplaylist() != 1 && $productcurrent->getTypeId() != 'grouped'): ?>
                                             <div class="ip-fbt">
                                                <input type="checkbox" name="fbt-product-select[]" id="product_<?php echo $productcurrent->getId() ?>" class="fbt-product-select" value="<?php echo $productcurrent->getId() ?>">
                                                <input type="text" class="fbt-qty" name="<?php echo $productcurrent->getId() ?>_qty" placeholder="0" value="1">
                                            </div>
                                        <?php endif; ?>
                                        <?php if ( ($showAddTo || $showCart) && $productcurrent->getTypeId() != 'grouped'): ?>
                                            <div class="product actions product-item-actions">
                                                <?php if ($showCart && $helper->getShowAddtocartsgnbtn()): ?>
                                                    <div class="actions-primary">
                                                        <?php if ($productcurrent->isSaleable()): ?>
                                                            <?php if ($productcurrent->getTypeInstance()->hasRequiredOptions($productcurrent)): ?>
                                                                <button class="action tocart primary" type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php else: ?>
                                                                <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($productcurrent), ['product' => $productcurrent->getEntityId()])
                                                                ?>
                                                                <button class="action tocart primary" type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php endif; ?>
                                                        <?php else: ?>
                                                            <?php if ($productcurrent->getIsSalable()): ?>
                                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                </div>
                            </div>
                        </li>
                    <?php endif; ?>
                <!-- end -->
                <?php $iterator = 1; $i = 1;?>
                <?php foreach ($items as $_item): ?>
                <?php //if ($_item->getTypeId() == 'grouped') continue; ?>
                <?php if ($limit == $i) break;?>
                <?php $available = ''; ?>
                <?php if (!$_item->isComposite() && $_item->isSaleable()): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <?php $available = 'related-available'; ?>
                    <?php endif; ?>
                <?php endif; ?>
                
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item li'.$i.' fbt_'.$_item->getId().' product product-item">' : '</li><li class="item li'.$i.' fbt_'.$_item->getId().' product product-item">' ?>
    
                <div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?>">
                    <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                        <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                            <?php echo $block->escapeHtml($_item->getName()) ?></a>
                        </strong>
                        <div class="price-fbt-item" style="<?php echo $helper->getShowPrice()? '':'display:none' ?>">
                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                        </div>
                            <?php if ($templateType): ?>
                                <?php echo $block->getReviewsSummaryHtml($_item, 'short',true) ?>
                            <?php endif; ?>
                            <?php if ($helper->getDisplaylist() != 1 && $_item->getTypeId() != 'grouped'): ?>
                                 <div class="ip-fbt">
                                    <input type="checkbox" name="fbt-product-select[]" id="product_<?php echo $_item->getId() ?>" class="fbt-product-select" value="<?php echo $_item->getId() ?>">
                                    <input type="text" class="fbt-qty" name="<?php echo $_item->getId() ?>_qty" placeholder="0" value="1">
                                </div>
                            <?php endif; ?>
                            <?php if (($showAddTo || $showCart) && $_item->getTypeId() != 'grouped' ): ?>
                                <div class="product actions product-item-actions">
                                    <?php if ($showCart && $helper->getShowAddtocartsgnbtn()): ?>
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <button class="action tocart primary" type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                    ?>
                                                    <button class="action tocart primary" type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                <?php $i++;endforeach ?>
            </ol>
        </div>
    </div>
</div>
<?php if ($helper->getDisplaylist() == 1): ?>
<table class="fbt-preview1">
    <thead>
        <tr>
            <th>
                <?php if ($helper->getShowAddalltocartbtn() || $helper->getShowAddalltowishlistbtn()): ?>
                    <input type="checkbox" name="" value="" class="fbt-add-all-product" checked>
                <?php endif ?>
            </th>
            <th><?php echo __('Products Name')?></th>
            <th><?php echo __('Qty')?></th>
            <th><?php echo __('Unit Price')?></th>
        </tr>
    </thead>
    <tbody>
    <?php $j = 1; ?>
    <?php if ($helper->getShowCurentProduct()) : ?>
    <?php $kj[0] = 0; $productcurrent = $block->getCurrentProduct() ;?>
        <tr>
            <td>
                <?php if ($productcurrent->getTypeId() != 'grouped'): ?>
                    <input type="checkbox" name="fbt-product-select[]" id="product_<?php echo $productcurrent->getId() ?>" class="fbt-product-select" value="<?php echo $productcurrent->getId() ?>" checked>
                <?php endif; ?>
            </td>
            <td>
                <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($productcurrent->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($productcurrent) ?>">
                            <?php echo $block->escapeHtml($productcurrent->getName()) ?></a>
                        </strong>
            </td>
            <td>
                <?php if ($productcurrent->getTypeId() != 'grouped'):?>
                <input type="text" class="fbt-qty" name="<?php echo $productcurrent->getId() ?>_qty" placeholder="0" value="1">
                <?php endif; ?>
            </td>
            <td><?php /* @escapeNotVerified */ echo $block->getProductPrice($productcurrent); ?></td>
        </tr>
     <?php endif; ?>
    <?php foreach ($items as $_item): ?>
        <?php //if ($_item->getTypeId() == 'grouped') continue; ?>
        <?php if ($limit == $j) break;?>
        <tr>
            <td>
                <?php if ($_item->getTypeId() != 'grouped'):?>
                <input type="checkbox" name="fbt-product-select[]" id="product_<?php echo $_item->getId() ?>" class="fbt-product-select" value="<?php echo $_item->getId() ?>" checked>
                <?php endif; ?>
            </td>
            <td><strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                            <?php echo $block->escapeHtml($_item->getName()) ?></a>
                        </strong></td>
            <td>
                <?php if ($_item->getTypeId() != 'grouped'):?>
                <input type="text" class="fbt-qty" name="<?php echo $_item->getId() ?>_qty" placeholder="0" value="1">
                <?php endif; ?>
            </td>
            <td><?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?></td>
        </tr>
     <?php $kj[$j] = $j; $j++;endforeach ?>
    </tbody>
</table>
<?php else: ?>
    <table class="fbt-preview2">
        <tbody>
        </tbody>
    </table>
<?php endif ?>
<?php if ($helper->getShowAddalltocartbtn() || $helper->getShowAddalltowishlistbtn()): ?>
<div class="fbt-action">
    <?php if ($helper->getDisplaylist() != 1): ?>
        <label><input type="checkbox" name="" value="" class="fbt-add-all-product">Select all products.</label>
    <?php endif ?>
    <?php if ($helper->getShowAddalltocartbtn()): ?>
        <button type="button" title="Add all products to Cart" style="background: #<?php echo $helper->getLBackgroundBtnCart() ?>; border:1px solid #<?php echo $helper->getLBackgroundBtnCart() ?>;color: #<?php echo $helper->getLColorBtnCart();?>" class="action fbtaddtocart primary"><span><?php echo __($helper->getLTextBtnCart()) ?></span><span class="total_products"></span></button>
    <?php endif ?>
    <?php if ($helper->getShowAddalltowishlistbtn()): ?>
        <button type="button" title="Add all products to Wishlist" style="background: #<?php echo $helper->getLBackgroundBtnWl() ?>; border:1px solid #<?php echo $helper->getLBackgroundBtnWl() ?>;color: #<?php echo $helper->getLColorBtnWl();?>" class="action fbtaddtowishlist primary"><span><?php echo __($helper->getLTextBtnWl()) ?></span><span class="total_products"></span></button>
    <?php endif ?> 
</div>
<?php endif ?>
</form>
<?php endif;?>
<div id="bss_fbt_cart_popup"></div>
<div class="slide-n-fbt" style="display: none;"></div>
<script type="text/javascript">
    require(['jquery','mage/mage','Bss_FBT/js/ajax','Bss_FBT/js/jquery.fancybox','Bss_FBT/js/owl.carousel.min'],function($){
        ajaxCart = new BssAjaxCart();
        ajaxCart.init('<?php  echo $storeManager->getStore()->getBaseUrl().'fbt/cart/'; ?>');
        $('.fbt-product-list .product-reviews-summary').each(function(){
            if($(this).hasClass('empty')) $(this).remove();
        })

        function reinitcarousel(rm,v) //When you click on any tab
        {
            var js_array = [<?php echo '"'.implode('","', $kj).'"' ?>];

            if (!rm) {
                $('.fbt .product-items .fbt_' + v).clone().appendTo('.slide-n-fbt');
                $('.fbt .product-items .fbt_' + v).remove();
            }else{
                $('.slide-n-fbt .fbt_' + v).clone().appendTo('.fbt .product-items');
                $('.slide-n-fbt .fbt_' + v).remove();
            }
            $('.owl-wrapper .owl-item').each(function(){
                if($(this).find('li').length == 0 ) $(this).remove();  
            })
            owl.data('owlCarousel').destroy();
            owl.owlCarousel({
            // Most important owl features
                items : <?php echo $helper->getLItemslide() ?>,
                stagePadding: 50,
                margin:10,
                itemsCustom : false,
                itemsDesktop : [1199,<?php echo $helper->getLItemslide() ?>],
                itemsDesktopSmall : [980,3],
                itemsTablet: [768,2],
                itemsTabletSmall: false,
                itemsMobile : [479,2],
                singleItem : false,
                itemsScaleUp : false,
             
                //Basic Speeds
                // slideSpeed : ,
                paginationSpeed : <?php echo (int)$helper->getLSpeedslide() ?>,
                rewindSpeed : 1000,
             
                //Autoplay
                autoPlay : <?php echo $helper->getLAutoslide()? 'true':'false' ?>,
                stopOnHover : true,
             
                // Navigation
                navigation : true,
                navigationText : ["",""],
                rewindNav : true,
                scrollPerPage : false,
             
                //Pagination
                pagination : false,
                paginationNumbers: false,
                afterInit: evCall, 
            })
            $.each(js_array,function(index,value){
                console.log(value);
               $('.owl-wrapper').append($('.owl-item .li'+ value).parent());    // add . here
            })
        }
        function sortMe(a, b) {
            return a.className > b.className;
        }
        $('.fbt-add-all-product').on('click',function(){
             if($(this).is(':checked')) {
                $('.fbt-add-all-product').prop( "checked", true );
                $('.fbt-product-select').each(function(){
                    if (!$(this).is(':checked')) {
                        $(this).trigger('click');
                    }
                })
             }else{
                $('.fbt-add-all-product').prop( "checked", false );
                $('.fbt-product-select').each(function(){
                    if ($(this).is(':checked')) {
                        $(this).trigger('click');
                    }
                })
             }
         })

        var displaylist = <?php echo $helper->getDisplaylist() ?>;
        var shpreview = <?php echo $helper->getShowPreview()? '1':'0'?>;

        if (displaylist == '1') {
            $('.fbt-product-select').on('click',function(){
                 if($(this).is(':checked')) {
                    $('.fbt_' + $(this).val()).show();
                    // reinitcarousel($(this).val());
                    reinitcarousel(true,$(this).val());
                 }else{
                    $('.fbt_' + $(this).val()).hide();
                    reinitcarousel(false,$(this).val());
                 }
             })
        }else{
             $('.fbt-product-select').on('click',function(){
                 if($(this).is(':checked')) {
                 }else{

                 }
                 preview(shpreview);
             })
            $('.fbt-qty').on('input',function(e){
                preview(shpreview);
            })
        }

        function preview() {
            if (shpreview == '1') {
                var html = '';
                var preview = '';
                $('.products-fbt .item').each(function(){
                    if ($(this).find('.fbt-product-select').is(':checked')) {
                       preview += '<tr><td>'+ $(this).find('.product-item-name a').text() +'</td><td>' + $(this).find('.fbt-qty').val()+'</td><td>'+ $(this).find('.price-box').html() +'</td></tr>'; 
                    }
                })
                if (preview !='') {
                    html = '<tr><td>Products Name</td><td>Qty</td><td>Unit Price</td></tr>' ;
                }
                html += preview; 
                $('.fbt-preview2 tbody').html(html);
            }
        }
        
        var owl = $('.fbt .product-items');

        owl.owlCarousel({
            // Most important owl features
            items : <?php echo $helper->getLItemslide() ?>,
            stagePadding: 50,
            margin:10,
            itemsCustom : false,
            itemsDesktop : [1199,<?php echo $helper->getLItemslide() ?>],
            itemsDesktopSmall : [980,3],
            itemsTablet: [768,2],
            itemsTabletSmall: false,
            itemsMobile : [479,2],
            singleItem : false,
            itemsScaleUp : false,
         
            //Basic Speeds
            // slideSpeed : ,
            paginationSpeed : <?php echo (int)$helper->getLSpeedslide() ?>,
            rewindSpeed : 1000,
         
            //Autoplay
            autoPlay : <?php echo $helper->getLAutoslide()? 'true':'false' ?>,
            stopOnHover : true,
         
            // Navigation
            navigation : true,
            navigationText : ["",""],
            rewindNav : true,
            scrollPerPage : false,
         
            //Pagination
            pagination : false,
            paginationNumbers: false,
            afterInit: evCall, 
        })
        function evCall(){

        }
        // owl.on('                                                                                                                                                                                                                                                                                                                                                                                                 ', '.owl-wrapper', function (e) {
        //     if (e.deltaY>0) {
        //         owl.trigger('owl.next');
        //     } else {
        //         owl.trigger('owl.prev');
        //     }
        //     e.preventDefault();
        // });
    });
</script>
<?php endif ?>