<?php $product = $this->getCurrentProduct() ?>

<?php if($product && $product->getCheckDeliveryEnable()==1): ?>

	<form data-mage-init='{"validation": {}}' class="form" id="checkDelivery-form" method="post" autocomplete="off" onSubmit="return checkPostcode()">

	   <fieldset class="fieldset">

		   <legend class="legend"><span><?php echo __('Check Delivery') ?></span></legend><br>
		   

			<div class="field required col-md-8 col-xs-8 no-padding">

				<label for="delivery_postcode" class="label col-md-3"><span><?php echo __('Pincode') ?></span></label>

				<div class="control custom-width col-md-3 col-xs-3">

					<input type="text" name="postcode" id="delivery_postcode" value="" title="<?php echo __('Pincode') ?>" class="input-text del" data-validate="{required:true, 'validate-digits':true}">

				</div>

			</div>

			

			

			<div class="actions-toolbar col-md-2 col-xs-4 no-padding">

			<div class="primary">

				<button type="submit" class="action submit primary col-md-2 col-xs-2" title="<?php  echo __('Check') ?>"><span><?php echo __('Check') ?></span></button>

			</div>

			</div>

			

			

			<div class="message"></div>
	

			

	   </fieldset>

	   		<br><br><label>Need expert advice to buy the right product? Call our expert on 8976666660</label><br><br>

	</form>
	<script type="text/x-magento-init">

		{

			"#checkDelivery-form": {

				"validation": {}

			}

		}

	</script>

	<script>

		function checkPostcode() {

			var deliveryMessage = jQuery('#checkDelivery-form .message');

			deliveryMessage.removeClass('success').removeClass('error').hide();

			var deliveryForm = jQuery('#checkDelivery-form');

			if(deliveryForm.valid()) {

				jQuery.ajax({

					type: "POST",

					url: '<?php echo $this->getUrl('checkDelivery/postcode/check',array('id'=>$product->getId())) ?>',

					data: deliveryForm.serialize(),

					dataType: "json",

					showLoader: true,

					success: function(response) {

						deliveryMessage.addClass(response.type).html(response.message).show();

					}

				});

			}

			return false;

		}

	</script>

<?php endif; ?>

