<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */ ?>

<?php $_item = $block->getItem() ?>
<?php $_order = $block->getItem()->getOrderItem()->getOrder(); ?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$prod = $objectManager->get('Magento\Catalog\Model\Product')->load($_item->getProductId());
$hsnCode=$prod->getHsncode();

if(!($hsnCode = $prod->getHsncode()))
			$hsnCode =  'N/A';
		
?>
<tr id="order-item-row-<?php /* @escapeNotVerified */ echo $_item->getId() ?>">
    <td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <strong class="product name product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?></strong>
        <?php if ($_options = $block->getItemOptions()): ?>
        <dl class="item-options">
        <?php foreach ($_options as $_option) : ?>
            <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
            <?php if (!$block->getPrintStatus()): ?>
                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="tooltip wrapper"<?php endif; ?>>
                    <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                    <div class="tooltip content">
                        <dl class="item options">
                            <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                            <dd><?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?></dd>
                        </dl>
                    </div>
                    <?php endif; ?>
                </dd>
            <?php else: ?>
                <dd><?php echo $block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
            <?php endif; ?>
        <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?php echo $addInfoBlock->setItem($_item->getOrderItem())->toHtml(); ?>
        <?php endif; ?>
        <?php echo $block->escapeHtml($_item->getDescription()) ?>
    </td>
    
        <td class="col sku" data-th="<?php echo $block->escapeHtml(__('HSNCODE')); ?>"><?php /* @escapeNotVerified */ echo $hsnCode ?></td>

    <td class="col sku" data-th="<?php echo $block->escapeHtml(__('SKU')); ?>"><?php /* @escapeNotVerified */ echo $block->prepareSku($block->getSku()) ?></td>
    <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
        <?php echo $block->getItemPriceHtml(); ?>
    </td>
    <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty Invoiced')); ?>">
        <span class="qty summary"><?php /* @escapeNotVerified */ echo $_item->getQty()*1 ?></span>
    </td>
     <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('CGST')); ?>">
     	<table>
              <tbody style="background:none;text-align:center">
                 <tr>
                     <td><?php echo round($_item->getcgst_percent(),2);?></span></td>
                     <td><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_item->getCgstCharge(),true,false);  ?></span></td>
                 </tr>
           </table>
       
    </td>
     <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('SGST')); ?>">
        <table>
            <tbody style="background:none;text-align:center">
            	<tr>
                	<td><?php echo round($_item->getsgst_percent(),2);?></span></td>
                    <td><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_item->getSgstCharge(),true,false);  ?></span></td>
                </tr>
        </table>
    </td>
     <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('IGST')); ?>">
       <table>
                          <tbody style="background:none;text-align:center">
                            <tr>
                                <td><?php echo round($_item->getigst_percent(),2);?></span></td>
                                <td><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_item->getIgstCharge(),true,false);  ?></span></td>
                            </tr>
                        </table>
    </td>
    <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
        <?php echo $block->getItemRowTotalHtml(); ?>
    </td>
</tr>
