<?php
/**
* BSS Commerce Co.
*
* NOTICE OF LICENSE
*
* This source file is subject to the EULA
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://bsscommerce.com/Bss-Commerce-License.txt
*
* =================================================================
*                 MAGENTO EDITION USAGE NOTICE
* =================================================================
* This package designed for Magento COMMUNITY edition
* BSS Commerce does not guarantee correct work of this extension
* on any other Magento edition except Magento COMMUNITY edition.
* BSS Commerce does not provide extension support in case of
* incorrect edition usage.
* =================================================================
*
* @category   BSS
* @package    Bss_AddMultipleProducts
* @author     Extension Team
* @copyright  Copyright (c) 2015-2016 BSS Commerce Co. ( http://bsscommerce.com )
* @license    http://bsscommerce.com/Bss-Commerce-License.txt
*/
?>
<?php 
	$helper = $this->helper('Bss\FBT\Helper\Data');
	$imageHelper = $this->helper('Magento\Catalog\Helper\Image');
	$product = $block->getProduct(); 
	$type_add = $block->getTypeadd();
	$product_success = isset($product['success'])? $product['success'] : null;
	$product_fail = isset($product['errors'])? $product['errors'] : null;
	$cart = $this->helper('\Magento\Checkout\Helper\Cart')->getCart();
	$activeCountdown = $helper->getPActivecountdown();
	$showContinue = $helper->getPShowContinueBtn();
	$showCheckoutLink = $helper->getPShowminicheckout();
	$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager = $_objectManager->get('\Magento\Store\Model\StoreManagerInterface');

?>
<div class="popup">
	<div class="header">
		<span><?php echo __('Shopping Cart'); ?></span>
	</div>
	<?php if ($block->getTypeadd() == 'single' && !$product_fail ): ?>
	<p class="message">
		<?php echo __('You added '); ?>

			<a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $product->getName(); ?>">
		            <?php echo $product->getName();?>
		    </a>
        <?php echo $block->getRelatedAdded() ? __(' and related products') : ''; ?>
        <?php echo __(' to your shopping cart'); ?>
	</p>
	<?php endif ?>

	<?php //if($helper->isShowProductImage()) :?>
		<?php if ($block->getTypeadd() == 'muntiple' && $product_success): ?>
			<p class="message"><span><?php echo __('You have added the following items to the cart: '); ?></span></p>
			<div class="product-image">
				<div id="product-slider" class="content-slider">
			<?php foreach ($product_success as  $productId): ?>
				<?php $products = $_objectManager->create('\Magento\Catalog\Model\Product')->load($productId); 

				?>
					<div  class="item product-info">
						<div class="product-image-aj">
							<img  class="" src="<?php echo $imageHelper->init($products, 'category_page_list', array('height' => 100, 'width'=> 100))->getUrl();?>">
						</div>
						<a href="<?php echo $products->getProductUrl() ?>" title="<?php echo $products->getName(); ?>">
		            		<span><?php echo $products->getName();?></span>
		        		</a>
		        		<?php if($helper->getPShowprice()) :?>
						<p>
						<?php if ($products->getTypeId() =='bundle') : ?>
	                        <?php $price_bundle = $_objectManager->get('Magento\Bundle\Model\Product\Price')->getTotalPrices($products); ?>
	                            <span class="price-from">
	                            <?php echo __('From:')?> <?php echo  $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($price_bundle[0], true, false); ?>
	                            </span>
	                            <span class="price-to">
	                            <?php echo __('To:')?> <?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($price_bundle[1], true, false); ?>
	                            </span>
	                    <?php else : ?>
	                        <span>
	                        <?php 
	                            echo  $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($products->getFinalPrice(), true, false);
	                        ?>
	                        </span>
	                    <?php endif; ?>
						</p>
						<?php endif; ?>
					</div>				
			<?php endforeach ?>
				</div>
			</div>
		<?php endif; ?>
		<?php if ($block->getTypeadd() == 'single' && !$product_fail): ?>
			<div class="product-image">
				<img src="<?php echo $imageHelper->init($product, 'category_page_list', array('height' => 100 , 'width'=> 100))->getUrl();?>">
				<?php if($helper->getPShowprice()) :?>
					<div>
						<span><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($product->getFinalPrice(), true, false);?></span>
					</div>
				<?php endif; ?>
			</div>
		<?php endif ?>
	<?php //endif; ?>
	<?php if ($product_fail): ?>
	<form action="<?php echo $storeManager->getStore()->getBaseUrl().'fbt/cart/addMultiple';?>" method="post" id="product_fbt_form_popup" data-mage-init='{"validation":{}}'>
		<?php echo $this->getBlockHtml('formkey')?>
		<div class="product-info-er">
			<?php $i = 1 ;foreach ($product_fail as $productId => $mess_fail): ?>
		    <?php $_product = $_objectManager->create('\Magento\Catalog\Model\Product')->load($productId); ?>
			<div class="item-er-pu">
				<p class="messages-error">
					<?php $mess_fails = explode('.',$mess_fail);?>
		            <span ><?php echo $mess_fails[0] ?></span>
				</p>
				<div class="item-info-er">
					<div class="item-img-er">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image-<?php echo $_product->getId(); ?>">
		                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
		                    src="<?php echo $imageHelper->init($_product, 'category_page_list', array('height' => 80 , 'width'=> 80))->getUrl();?>"
		                    alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
		                </a>
					</div>
					<div class="info-er-pu">
						<p><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName(); ?>"><?php echo $_product->getName(); ?></a></p>
						<p class="price-box">    
		                        <?php if ($_product->getTypeId() =='bundle') : ?>
		                        <?php $price_bundle = $_objectManager->get('Magento\Bundle\Model\Product\Price')->getTotalPrices($_product); ?>
		                            <p class="price-from">
		                            <?php echo __('From:')?> <?php echo  $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($price_bundle[0], true, false); ?>
		                            </p>
		                            <p class="price-to">
		                            <?php echo __('To:')?> <?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($price_bundle[1], true, false); ?>
		                            </p>
		                        <?php else : ?>
		                        <?php 
		                            echo  $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_product->getFinalPrice(), true, false);
		                        ?>
		                        <?php endif; ?>
		                </p>
		                <div class="option-er-pu">
		               		<input type="hidden" name="productid" value="<?php echo $_product->getId() ?>">
		                        <?php echo $block->getProductOptionsHtml($_product,$configurable = true); ?>
		                </div>
		                <input type="hidden" name="fbt-product-select[]" class="fbt-product-select" id="product-select-<?php echo $_product->getId() ?>" value="<?php echo $_product->getId() ?>">
		                <div class="product-qty-er">
		                <span><?php echo __('Qty'); ?></span>               
		                <input type="text" class="quantity" name="<?php echo $_product->getId() ?>_qty" id="qty-<?php echo $_product->getId() ?>" value="<?php echo __('1') ?>">
		                </div>
					</div>
					<div class="remove-er-pu">
						<span class="remove"></span>
					</div>
					<div style="clear: both"></div>
				</div>
			</div>
			<?php $i++; endforeach; ?>
		</div>
		<button type="submit" title="Add to Cart" style="background: #<?php echo $helper->getPBackgroundBtn() ?>; border:1px solid #<?php echo $helper->getPBackgroundBtn() ?>;color: #<?php echo $helper->getPColorTextBtn();?>" class="action primary " id="product-addtocart-button-er-pu">
                <span><?php echo __($helper->getPTextBtn())?></span>
        </button>
	</form>
	<?php endif ?>
	<?php if($helper->getPShowminicart()) :?>
		<div class="cart-info">
			<div class="items-count">
				<span>
					<?php echo ($cart->getItemsQty() > 1) ? __('There are ') : __('There is '); ?>
					<a href="<?php echo $block->getUrl('checkout/cart'); ?>">
						<?php 
							echo $cart->getItemsQty();
							echo ($cart->getItemsQty() > 1) ? __(' items') : __(' item'); 
						?>
					</a>
					<?php echo __(' in your cart.'); ?>
				</span>
			</div>
			<div class="subtotal">
				<span>
					<?php 
						$quote = $this->helper('\Magento\Checkout\Helper\Cart')->getQuote();
						echo __('Cart Subtotal: ');
						echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($quote->getSubtotal(), true, false);
					?>
				</span>
			</div>
			<?php if($showCheckoutLink && $cart->getItemsQty() > 0) : ?>
			<div class="checkout-link">
				<a href="<?php echo $block->getUrl('checkout')?>">
					<span><?php echo __('Go to checkout'); ?></span>
				</a>
			</div>
			<?php endif; ?>
		</div>
	<?php endif; ?>

	<div class="action clearfix" style="margin-top: 10px;">
		<div class="btn-viewcart <?php if(!$showContinue) { echo 'full-width'; }?>">
			<a href="<?php echo $block->getUrl('checkout/cart') ?>" title="<?php echo __('View Cart'); ?>" class="view-cart">
                <button class="viewcart" style="background: #<?php echo $helper->getPBackgroundBtnV() ?>; border:1px solid #<?php echo $helper->getPBackgroundBtnV() ?>;color: #<?php echo $helper->getPColorTextBtnV();?>" type="button" title="<?php echo __($helper->getPTextBtnV())?>">
                	<span><?php echo __($helper->getPTextBtnV()); ?></span>
                	<?php if($activeCountdown == '2') :?>
                		<span class="<?php echo ($activeCountdown == '2') ? 'countdown' : ''; ?>">(<?php echo $helper->getPCountdowntime(); ?>)</span>
                	<?php endif; ?>
                </button>
            </a>
		</div>

		<?php if($showContinue) : ?>
		<div class="btn-continue">
			<button class="continue" style="background: #<?php echo $helper->getPBackgroundBtnC() ?>; border:1px solid #<?php echo $helper->getPBackgroundBtnC() ?>;color: #<?php echo $helper->getPColorTextBtnC();?>" type="button" title="<?php echo __($helper->getPTextBtnC())?>">
            	<span><?php echo __($helper->getPTextBtnC()); ?></span>
            		<?php if($activeCountdown == '1') :?>
                		<span class="<?php echo ($activeCountdown == '1') ? 'countdown' : ''; ?>">(<?php echo $helper->getPCountdowntime(); ?>)</span>
                	<?php endif; ?>
            </button>
		</div>
		<?php endif; ?>
	</div>
</div>

<script type="text/javascript">
	var count;
	require(['jquery','mage/mage'],function($){
		var dataForm = $('#product_addmuntile_form_popup');
   		dataForm.mage('validation', {});
		$('.btn-continue .continue').click(function(){
			$.fancybox.close();
			clearInterval(count);
		});
		$('.remove-er-pu').on('click',function(){
			$(this).parents('.item-er-pu').remove();
			if ( $('.item-er-pu').length == 0) {
				$('#product-addtocart-button-er-pu').remove();
			}
		})
		$('.option-er-pu').each(function(){
			$productid = $(this).find('input[name="productid"]').val();
			$(this).find('input').each(function(){
				$(this).attr('name',$productid + '_' + $(this).attr('name'));
			})
			$(this).find('textarea').each(function(){
				$(this).attr('name',$productid + '_' + $(this).attr('name'));
			})
			$(this).find('select').each(function(){
				$(this).attr('name',$productid + '_' + $(this).attr('name'));
			})
		})
		ajaxCartpu = new BssAjaxCart();
		$('#product-addtocart-button-er-pu').on('click',function(e){
			e.preventDefault();
			var form = $('form#product_fbt_form_popup');
			// if ($(form)){
                // $(form).validate();
                if ($(form).valid()) {
					var addUrl = $(form).attr('action');
            		var data = $(form).serialize();
            		ajaxCartpu.sendAjax(addUrl, data);
            	}
            // }
            return false;
		})
		var countDown = <?php echo $helper->getPCountdowntime(); ?>;

		count = setInterval(function(){
			countDown -= 1;
			$('span.countdown').text("(" + countDown + ")");
			if(countDown == 0) {
				$('span.countdown').parent().trigger("click");
				clearInterval(count);
			}
		}, 1000);


		var owl = $('#product-slider');

		owl.owlCarousel({
		    // Most important owl features
		    items : <?php echo $helper->getPItemslide() ?>,
		    stagePadding: 50,
    		margin:10,
		    itemsCustom : false,
		    itemsDesktop : [1199,<?php echo $helper->getPItemslide() ?>],
		    // itemsDesktopSmall : [980,3],
		    itemsTablet: [768,2],
		    itemsTabletSmall: false,
		    itemsMobile : [479,1],
		    singleItem : false,
		    itemsScaleUp : false,
		 
		    //Basic Speeds
		    slideSpeed : <?php echo $helper->getPSpeedslide() ?>,
		    paginationSpeed : 800,
		    rewindSpeed : 1000,
		 
		    //Autoplay
		    autoPlay : <?php echo $helper->getPAutoslide()? 'true':'false'?>,
		    stopOnHover : true,
		 
		    // Navigation
		    navigation : true,
		    navigationText : ["",""],
		    rewindNav : true,
		    scrollPerPage : false,
		 
		    //Pagination
		    pagination : false,
		    paginationNumbers: false,
		 	afterInit: evCall, 
		})
		function evCall(){

			// var maxHeight = Math.max.apply(null, $(".item.product-info").map(function ()
			// {
			//     return $(this).height();
			// }).get());
			// $(".item.product-info").each(function(){
			// 	$(this).height(maxHeight + 5);
			// })
		}
		
	});
</script>