<style type="text/css" media="screen">
.sort-fbt {
    width: 100%;
    max-width: 350px;
    background-color: #FFF;
    margin-top: 25px;
    list-style-type: none;
    padding: 0;
    box-sizing: border-box;
    height: 185px;
    overflow-x: hidden;
    overflow-y: auto;
    border: 1px solid #aaa;
}

.sort-fbt li {
    line-height: 30px;
    border-bottom: 1px solid #CCC;
    font-size: 13px;
    margin: 0;
    padding: 5px;
    font-size: 14px;
    line-height: 20px;
    height: 30px
}

.sort-fbt li:hover {
    background: #F6F6F6;
    cursor: pointer
}
</style>
<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * BSS Commerce does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * BSS Commerce does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   BSS
 * @package    Bss_FBT
 * @author     Extension Team
 * @copyright  Copyright (c) 2015-2016 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
$itemtype = $block->getItemType();
$_sortitemtype = $itemtype;
$sortableString = $block->sortItemType();
if ($sortableString) {
    $_sortitemtype = []; 
    $sortitemtype = null;
    parse_str($sortableString, $sortitemtype);
    foreach ($sortitemtype['sort']  as $key => $value) {
        $_sortitemtype[$value] = $itemtype[$value];
    }
}
?>
<tr id="general_sort_fbt">
    <td class="label"><?php echo $this->element->getLabel(); ?></td>
    <td colspan="3" class="fbt-td">        
        <div style="clear: both"></div>
        <div class="fbt-form">
            <ul id="sort-fbt" data-list="sort" class="sort-fbt">
            <?php foreach ($_sortitemtype as $val=>$lable) { ?>
                <li id="sort-<?php echo $val; ?>" class="">
                    <span class="fbt-text"><?php echo $this->escapeHtml($lable); ?></span>
                </li>
            <?php } ?>
            </ul>
        </div>
        <p class="note" style="max-width: 600px;"><strong>Real Data:</strong> Frequently bought together products will be calculated in according to the frequency of appearance with the main product of orders in the selected time period.</p>
    </td>
</tr>
