<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$prod = $objectManager->get('Magento\Catalog\Model\Product')->load($_item->getProductId());
$hsnCode=$prod->getHsncode();

if(!($hsnCode = $prod->getHsncode()))
			$hsnCode =  'N/A';
		
?>
<tr>
    <td  class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= /* @escapeNotVerified */  __('SKU'); ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
         <P class="hsncode"><?= __("HSN CODE")?>: <?= $block->escapeHtml($hsnCode)?>
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options">
            <?php foreach ($block->getItemOptions() as $option): ?>
                <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                <dd>
                    <?= /* @escapeNotVerified */  nl2br($option['value']) ?>
                </dd>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <!-- magecomp start -->
    <td colspan="2" class="col subtotal" data-th="<?php echo $block->escapeHtml(__('CGST')); ?>">
     	<table style="width: 100%">
              <tbody style="background:none;text-align:center">
                 <tr>
                     <td><?php echo round($_item->getcgst_percent(),2)."%";?></span></td>
                     <td><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_item->getCgstCharge(),true,false);  ?></span></td>
                 </tr>
           </table>
       
    </td>
     <td colspan="2" class="col subtotal" data-th="<?php echo $block->escapeHtml(__('SGST')); ?>">
        <table style="width: 100%">
            <tbody style="background:none;text-align:center">
            	<tr>
                	<td><?php echo round($_item->getsgst_percent(),2)."%";?></span></td>
                    <td><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_item->getSgstCharge(),true,false);  ?></span></td>
                </tr>
        </table>
    </td>
     <td colspan="2" class="col subtotal" data-th="<?php echo $block->escapeHtml(__('IGST')); ?>">
       <table style="width: 100%">
                          <tbody style="background:none;text-align:center">
                            <tr>
                                <td><?php echo round($_item->getigst_percent(),2)."%";?></span></td>
                                <td><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_item->getIgstCharge(),true,false);  ?></span></td>
                            </tr>
                        </table>
    </td>
    <!-- magecomp End -->
    <td class="item-qty"><?= /* @escapeNotVerified */  $_item->getQtyOrdered() * 1 ?></td>
    <td class="item-price" style="text-align:center">
        <?= /* @escapeNotVerified */  $block->getItemPrice($_item); ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())): ?>
<tr>
    <td colspan="3" class="item-extra">
        <table class="message-gift">
            <tr>
                <td>
                    <h3><?= /* @escapeNotVerified */  __('Gift Message') ?></h3>
                    <strong><?= /* @escapeNotVerified */  __('From:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                    <br /><strong><?= /* @escapeNotVerified */  __('To:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                    <br /><strong><?= /* @escapeNotVerified */  __('Message:'); ?></strong>
                    <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php endif; ?>
